name: flutter_io_dev_tools

environment:
  sdk: '>=2.18.5 <3.0.0'

dev_dependencies:
  build_runner: ^2.3.2
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  code_excerpter:
    path: site-shared/packages/code_excerpter
  linkcheck: ^2.0.19
