name: docs_flutter_dev
publish_to: none

environment:
  sdk: ^3.1.0

dev_dependencies:
  # Used to enable easy access from the root directory.
  build_runner: ^2.4.6
  code_excerpter:
    path: site-shared/packages/code_excerpter
  code_excerpt_updater:
    path: site-shared/packages/code_excerpt_updater
  flutter_site:
    path: tool/flutter_site
