name: constraints
description: example for ui/layout/constraints
version: 1.0.0

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
