name: dash_site
description: Dart-based tools for flutter/website.
publish_to: none

environment:
  sdk: ^3.1.0

dependencies:
  args: ^2.4.2
  io: ^1.0.4
  linkcheck: ^3.0.0
  path: ^1.8.3
  
dev_dependencies:
  analysis_defaults:
    path: ../../site-shared/packages/analysis_defaults
