name: hero_animations
description: Hero animations

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
